version: "3"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: "${PORT}"
      DB_URI: "${DB_URI}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app

  db:
    image: ${DB_IMAGE}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:${DB_ROUTE}
